name: Deploy Backend

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - dev
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['14.x']
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: Install dependencies
      run: npm install
      working-directory: backend

    - name: Copy env variables
      run: |
        echo "DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING }}" > backend/.env.prod
        echo "PORT=${{ secrets.PORT }}" >> backend/.env.prod

    - name: Build
      run: npm run build --if-present
      working-directory: backend

    - name: Move backend files to root
      run: |
        cp -r backend/* .
        mv backend/.env.prod .  # Use mv to ensure the .env.prod file is moved

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "full-stack-banking-api"
        heroku_email: "agdpcloud@gmail.com"
