name: Deploy Full Stack Application

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'front-end/**'
      - 'backend/**'
  workflow_dispatch: 
  
jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        cd front-end
        npm install
    
    - name: Build project
      run: |
        cd front-end
        npm run build

    - name: Deploy to Azure Blob Storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch --account-name fullstackbankingweb --auth-mode key -d '$web' -s ./front-end/build/

    - name: Azure logout
      run: az logout

  deploy_backend:
    needs: deploy_frontend  # Ensure frontend is deployed before starting backend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['14.x']
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: Install dependencies
      run: npm install
      working-directory: backend

    - name: Copy env variables
      run: |
        echo "DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING }}" > backend/.env.prod
        echo "PORT=${{ secrets.PORT }}" >> backend/.env.prod

    - name: Build
      run: npm run build --if-present
      working-directory: backend

    - name: Move backend files to root
      run: |
        cp -r backend/* .
        mv backend/.env.prod .

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "full-stack-banking-api"
        heroku_email: "agdpcloud@gmail.com"
