name: Deploy Frontend

on:
  push:
    paths:
      - 'front-end/**'  # Only trigger when files in front-end directory change
    branches:
      - dev  # Trigger on push to main branch
      
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Adjust as per your project needs
    
    - name: Install dependencies
      run: |
        cd front-end
        npm install
    
    - name: Build project
      run: |
        cd front-end
        npm run build

    - name: List build directory
      run: |
        cd front-end/build
        ls -al

    # Clear existing files in $web container
    - name: Clear Azure Blob Storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob delete-batch --account-name fullstackbankingweb --auth-mode key -s '$web'

    # Deploy new files
    - name: Deploy to Azure Blob Storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch --account-name fullstackbankingweb --auth-mode key -d '$web' -s ./front-end/build/
      
    - name: Azure logout
      run: |
            az logout