# # Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# # More GitHub Actions for Azure: https://github.com/Azure/actions

# name: Deploy Backend

# on:
#   push:
#     paths:
#       - 'backend/**'  # Only trigger when files in front-end directory change
#     branches:
#       - dev
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Node.js version
#         uses: actions/setup-node@v3
#         with:
#           node-version: '16.x'

#       - name: npm install and build
#         run: |
#           cd backend
#           npm install
#           npm run build --if-present
#           echo "DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING }}" > .env.prod
#           echo "PORT=${{ secrets.PORT }}" >> .env.prod       

#       - name: Zip artifact for deployment
#         run: zip -r ../release.zip ./*

#       - name: Upload artifact for deployment job
#         uses: actions/upload-artifact@v3
#         with:
#           name: node-app
#           path: release.zip

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     environment:
#       name: 'production'
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

#     steps:
#       - name: Download artifact from build job
#         uses: actions/download-artifact@v3
#         with:
#           name: node-app

#       - name: Unzip artifact for deployment
#         run: unzip release.zip

#       - name: Azure Login
#         uses: azure/login@v1
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}

#       - name: 'Deploy to Azure Web App'
#         id: deploy-to-webapp
#         uses: azure/webapps-deploy@v2
#         with:
#           app-name: 'full-stack-bankin-app-api'
#           # slot-name: 'production'
#           publish-profile: ${{ secrets.AzureAppService_PublishProfile_1234 }}
#           package: .

name: Deploy Backend

on:
  push:
    paths:
      - 'backend/**'  # Only trigger when files in front-end directory change
    branches:
      - dev
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['14.x']
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - run: npm install
    - run: npm run build --if-present
    - run: echo "DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING }}" > .env.prod
    - run: echo "PORT=${{ secrets.PORT }}" >> .env.prod       


  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "full-stack-banking-api"
        heroku_email: "agdpcloud@gmail.com"

